modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "bluemap_opac"
version = "${version}"
displayName = "BlueMap-OPAC"
displayURL="https://github.com/unilock/BlueMap-OPAC"
authors="unilock"
description = '''
BlueMap + OPAC = <3
'''

[[dependencies.bluemap_opac]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bluemap_opac]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bluemap_opac]]
modId = "bluemap"
mandatory = true
versionRange = "[3.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bluemap_opac]]
modId = "openpartiesandclaims"
mandatory = true
versionRange = "[0.19.0,)"
ordering = "AFTER"
side = "BOTH"
